import type { Metadata } from "next";
import "./globals.css";
import { timesNow } from "../fonts";

export const metadata: Metadata = {
  title: "Grande Avenida",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={timesNow.className}>{children}</body>
    </html>
  );
}
